services:
  fatebook_beeminder_bridge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fatebook_beeminder_bridge
    env_file:
      - .env
    environment:
      - RUST_LOG=fatebook_beeminder_bridge=debug,reqwest=info
    restart: unless-stopped
    networks:
      - sgodilla-network

networks:
  sgodilla-network:
    driver: bridge
